# Railpack configuration for ultralytics deployment
# Modern alternative to Nixpacks with better Python support

[build]
# Python version specification
PYTHON_VERSION = "3.11"

# System dependencies for OpenCV and ultralytics
# Railpack automatically handles common Python package dependencies
system_packages = [
    "libgl1-mesa-dri",
    "libglib2.0-0", 
    "libsm6",
    "libxext6",
    "libxrender-dev",
    "libgomp1",
    "libgtk-3-0",
    "libgstreamer1.0-0",
    "libgstreamer-plugins-base1.0-0",
    "libavcodec-dev",
    "libavformat-dev",
    "libswscale-dev",
    "libfontconfig1",
    "libcairo2",
    "libgdk-pixbuf2.0-0",
    "libpango-1.0-0",
    "libharfbuzz0b",
    "libpangocairo-1.0-0",
    "libatk1.0-0",
    "libcairo-gobject2",
    "libjpeg-dev",
    "libpng-dev",
    "libtiff-dev",
    "libwebp-dev",
    "libopenjp2-7-dev"
]

[install]
# Standard pip install from requirements.txt
# Railpack automatically handles Python package dependencies
commands = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[runtime]
# Environment variables for headless operation
QT_QPA_PLATFORM = "offscreen"
DISPLAY = ":99"
OPENCV_IO_ENABLE_OPENEXR = "1"
ULTRALYTICS_SETTINGS = '{"runs_dir": "/tmp", "datasets_dir": "/tmp", "weights_dir": "/tmp"}'

[start]
# Start command
command = "gunicorn --bind 0.0.0.0:$PORT app:app"