# Railway configuration using Railpack builder
# Modern alternative to Nixpacks with better Python support

[build]
builder = "railpack"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
# Python version
RAILPACK_PYTHON_VERSION = "3.11"

# Environment variables for headless operation
QT_QPA_PLATFORM = "offscreen"
DISPLAY = ":99"
OPENCV_IO_ENABLE_OPENEXR = "1"
ULTRALYTICS_SETTINGS = '{"runs_dir": "/tmp", "datasets_dir": "/tmp", "weights_dir": "/tmp"}'

# Disable pip version check for faster builds
PIP_DISABLE_PIP_VERSION_CHECK = "1"
PIP_DEFAULT_TIMEOUT = "100"