# Minimal Railway configuration for ultralytics deployment
# Use this if the main railway.toml fails due to package compatibility

[build]
builder = "nixpacks"

[build.env]
PYTHON_VERSION = "3.11"
# Minimal system packages - only essential ones
APT_PACKAGES = "libgl1-mesa-dri libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1 libfontconfig1 libcairo2 libjpeg-dev libpng-dev"
# Simplified install command
NIXPACKS_INSTALL_CMD = "apt-get update && apt-get install -y libgl1-mesa-dri libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1 libfontconfig1 libcairo2 libjpeg-dev libpng-dev && pip install --upgrade pip setuptools wheel && pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu && pip install ultralytics>=8.0.0 sahi==0.11.14 && pip install -r requirements.txt"
# Environment variables for headless operation
QT_QPA_PLATFORM = "offscreen"
DISPLAY = ":99"
OPENCV_IO_ENABLE_OPENEXR = "1"
ULTRALYTICS_SETTINGS = '{"runs_dir": "/tmp", "datasets_dir": "/tmp", "weights_dir": "/tmp"}'

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT app:app"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3