# Railpack configuration for ultralytics deployment
# Modern alternative to Nixpacks with better Python support

[build]
# Python version specification
PYTHON_VERSION = "3.11"

# Build-time Apt packages (development headers and build tools)
buildAptPackages = ["python3-dev", "python3-pip", "build-essential", "libgl1-mesa-dev", "libglib2.0-dev", "libegl1-mesa-dev", "libglu1-mesa-dev", "mesa-common-dev", "libglfw3-dev", "libgthread-2.0-dev", "libxrender-dev", "libavcodec-dev", "libavformat-dev", "libswscale-dev", "libjpeg-dev", "libpng-dev", "libtiff-dev", "libwebp-dev", "libopenjp2-7-dev"]

# Deploy-time Apt packages (runtime libraries)
deployAptPackages = ["libgl1", "libglx-mesa0", "libgl1-mesa-dri", "libegl1-mesa", "libglu1-mesa", "mesa-utils", "libglfw3", "libglib2.0-0", "libsm6", "libxext6", "libgomp1", "libgthread-2.0-0", "libgtk-3-0", "libgstreamer1.0-0", "libgstreamer-plugins-base1.0-0", "libfontconfig1", "libcairo2", "libgdk-pixbuf2.0-0", "libpango-1.0-0", "libharfbuzz0b", "libpangocairo-1.0-0", "libatk1.0-0", "libcairo-gobject2"]

[install]
# Install Python dependencies
commands = [
    "pip install -r requirements.txt"
]

[runtime]
# Environment variables for headless operation
QT_QPA_PLATFORM = "offscreen"
DISPLAY = ":99"
OPENCV_IO_ENABLE_OPENEXR = "1"
ULTRALYTICS_SETTINGS = '{"runs_dir": "/tmp", "datasets_dir": "/tmp", "weights_dir": "/tmp"}'
LD_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/mesa:/usr/lib"

[start]
# Start command
command = "gunicorn --bind 0.0.0.0:$PORT app:app"